const jokes = [
    { id: 1, setup: "Why don’t programmers like nature?", punchline: "Too many bugs." },
    { id: 2, setup: "Why do Java developers wear glasses?", punchline: "Because they don’t C#." },
    { id: 3, setup: "I told my computer I needed a break...", punchline: "It froze." },
    { id: 4, setup: "Why did the developer go broke?", punchline: "Because he used up all his cache." },
    { id: 5, setup: "Why was the math book sad?", punchline: "Too many problems." },
    { id: 6, setup: "I tried to catch fog...", punchline: "I mist." },
    { id: 7, setup: "Why don’t skeletons fight?", punchline: "They don’t have the guts." },
    { id: 8, setup: "Parallel lines have so much in common...", punchline: "It’s a shame they’ll never meet." },
    { id: 9, setup: "I ate a clock yesterday...", punchline: "It was time-consuming." },
    { id: 10, setup: "Why did the scarecrow win an award?", punchline: "He was outstanding in his field." },

    { id: 11, setup: "There are 10 types of people...", punchline: "Those who understand binary and those who don’t." },
    { id: 12, setup: "Debugging is like being a detective...", punchline: "Where you are also the murderer." },
    { id: 13, setup: "My code doesn’t work, I have no idea why...", punchline: "My code works, I have no idea why." },
    { id: 14, setup: "I changed my password to 'incorrect'...", punchline: "Now it reminds me when I’m wrong." },
    { id: 15, setup: "Real programmers count from...", punchline: "0." },
    { id: 16, setup: "Why did the function return early?", punchline: "Because it had a date." },
    { id: 17, setup: "A SQL query walks into a bar...", punchline: "It asks: Can I join you?" },
    { id: 18, setup: "HTML and CSS are like a couple...", punchline: "One structures, the other styles." },
    { id: 19, setup: "AI won’t take your job...", punchline: "Someone using AI will." },
    { id: 20, setup: "I got fired from the keyboard factory...", punchline: "I wasn’t putting in enough shifts." },

    { id: 21, setup: "I’m not lazy...", punchline: "I’m on energy-saving mode." },
    { id: 22, setup: "I told my WiFi a joke...", punchline: "It didn’t get the connection." },
    { id: 23, setup: "My phone battery lasts longer than...", punchline: "My motivation." },
    { id: 24, setup: "I don’t need a hairstylist...", punchline: "My pillow gives me a new look every morning." },
    { id: 25, setup: "I’m reading a book on anti-gravity...", punchline: "I can’t put it down." },
    { id: 26, setup: "I started exercising...", punchline: "I stopped, but I started." },
    { id: 27, setup: "My brain has too many...", punchline: "Tabs open." },
    { id: 28, setup: "I’m not arguing...", punchline: "I’m just explaining why I’m right." },
    { id: 29, setup: "Life is short...", punchline: "And so is my attention span." },
    { id: 30, setup: "I tried being normal once...", punchline: "Worst two minutes of my life." },

    { id: 31, setup: "Why can’t you trust atoms?", punchline: "They make up everything." },
    { id: 32, setup: "Schrodinger’s cat walks into a bar...", punchline: "And doesn’t." },
    { id: 33, setup: "Why did the physicist break up?", punchline: "No chemistry." },
    { id: 34, setup: "I told a joke about infinity...", punchline: "It never ends." },
    { id: 35, setup: "Why are obtuse angles annoying?", punchline: "Because they’re never right." },
    { id: 36, setup: "A photon checks into a hotel...", punchline: "No luggage, it’s traveling light." },
    { id: 37, setup: "Time flies like an arrow...", punchline: "Fruit flies like a banana." },
    { id: 38, setup: "Why was the equal sign humble?", punchline: "It knew it wasn’t less or greater than anyone." },
    { id: 39, setup: "Why did the statistician drown?", punchline: "The river was shallow on average." },
    { id: 40, setup: "I love pressing F5...", punchline: "It’s refreshing." },

    { id: 41, setup: "I asked my dog what’s two minus two...", punchline: "He said nothing." },
    { id: 42, setup: "Why did the computer go to therapy?", punchline: "Too many bytes of trauma." },
    { id: 43, setup: "I opened the fridge and forgot why...", punchline: "Now I live there." },
    { id: 44, setup: "I tried to be productive...", punchline: "But Netflix had other plans." },
    { id: 45, setup: "My code works...", punchline: "I’m suspicious." },
    { id: 46, setup: "I cleaned my room...", punchline: "Just kidding." },
    { id: 47, setup: "Why did the chicken join a band?", punchline: "Because it had drumsticks." },
    { id: 48, setup: "I told my brain to focus...", punchline: "It went on vacation." },
    { id: 49, setup: "I need a six-month holiday...", punchline: "Twice a year." },
    { id: 50, setup: "If at first you don’t succeed...", punchline: "Redefine success." }
];

export default jokes;